// 逻辑类CQA_Lab_Element_Text源文件
// 本文件是由L3集成开发环境自动生成，在没有充分了解本文件的内容前，请不要随意修改本文件中的内容
// 否则可能带来严重后果。

#include "StdAfx.h"
#include "_CQA_Lab_Element_Text.h"

IMPLEMENT_L3CLASS(CQA_Lab_Element_Text,CL3Object,1)

BEGIN_L3PROPTABLE(CQA_Lab_Element_Text,CL3Object)
	L3PROP_STRING(AppID)
	L3PROP_STRING(Sample_Code)
	L3PROP_DATETIME(Arrive_Date)
	L3PROP_DATETIME(Report_Date)
	L3PROP_STRING(HeatID)
	L3PROP_LONG(UnitTypeID)
	L3PROP_LONG(UnitID)
	L3PROP_STRING(Sample_Address)
	L3PROP_STRING(Sample_Type)
	L3PROP_STRING(Sample_Count)
	L3PROP_STRING(C)
	L3PROP_STRING(Si)
	L3PROP_STRING(Mn)
	L3PROP_STRING(P)
	L3PROP_STRING(S)
	L3PROP_STRING(Cu)
	L3PROP_STRING(Ni)
	L3PROP_STRING(Cr)
	L3PROP_STRING(Mo)
	L3PROP_STRING(V)
	L3PROP_STRING(Nb)
	L3PROP_STRING(Al)
	L3PROP_STRING(AlS)
	L3PROP_STRING(Ti)
	L3PROP_STRING(B)
	L3PROP_STRING(Sb)
	L3PROP_STRING(Sn)
	L3PROP_STRING(As)
	L3PROP_STRING(Zn)
	L3PROP_STRING(Zr)
	L3PROP_STRING(Ca)
	L3PROP_STRING(W)
	L3PROP_STRING(Pb)
	L3PROP_STRING(Re)
	L3PROP_STRING(Ceq)
	L3PROP_STRING(N)
	L3PROP_STRING(H)
	L3PROP_STRING(O)
	L3PROP_STRING(CrNi)
	L3PROP_STRING(CrCu)
	L3PROP_STRING(CrNiCu)
	L3PROP_STRING(Other1)
	L3PROP_STRING(Other2)
	L3PROP_STRING(Other3)
	L3PROP_DATETIME(LogTime)
	L3PROP_LONG(DataLogMode)
	L3PROP_STRING(Operator)
END_L3PROPTABLE(CQA_Lab_Element_Text)

BEGIN_L3METHODMAP(CQA_Lab_Element_Text,CL3Object)
END_L3METHODMAP()

BEGIN_L3EVENTSINK_MAP(CQA_Lab_Element_Text,CL3Object)
END_L3EVENTSINK_MAP(CQA_Lab_Element_Text)

CQA_Lab_Element_Text::CQA_Lab_Element_Text(void)
{
}

CQA_Lab_Element_Text::~CQA_Lab_Element_Text(void)
{
}
