// 逻辑类CQA_Lab_SlagEle源文件
// 本文件是由L3集成开发环境自动生成，在没有充分了解本文件的内容前，请不要随意修改本文件中的内容
// 否则可能带来严重后果。

#include "StdAfx.h"
#include "_CQA_Lab_SlagEle.h"

IMPLEMENT_L3CLASS(CQA_Lab_SlagEle,CL3Object,1)

BEGIN_L3PROPTABLE(CQA_Lab_SlagEle,CL3Object)
	L3PROP_STRING(AppID)
	L3PROP_DATETIME(Arrive_Date)
	L3PROP_DATETIME(Report_Date)
	L3PROP_STRING(HeatID)
	L3PROP_STRING(Sample_Address)
	L3PROP_STRING(Sample_Type)
	L3PROP_STRING(Sample_Count)
	L3PROP_STRING(Sample_Code)
	L3PROP_STRING_LEN(TFe,15)
	L3PROP_STRING_LEN(FeO,15)
	L3PROP_STRING_LEN(SiO2,15)
	L3PROP_STRING_LEN(TCa,15)
	L3PROP_STRING_LEN(CaO,15)
	L3PROP_STRING_LEN(MgO,15)
	L3PROP_STRING_LEN(Al2O3,15)
	L3PROP_STRING_LEN(MnO,15)
	L3PROP_STRING_LEN(TiO2,15)
	L3PROP_STRING_LEN(P2O5,15)
	L3PROP_STRING_LEN(S,15)
	L3PROP_STRING_LEN(R,15)
	L3PROP_DATETIME(LogTime)
	L3PROP_LONG(DataLogMode)
	L3PROP_STRING(Operator)
	L3PROP_FLOAT(Cr2O3)
END_L3PROPTABLE(CQA_Lab_SlagEle)

BEGIN_L3METHODMAP(CQA_Lab_SlagEle,CL3Object)
END_L3METHODMAP()

BEGIN_L3EVENTSINK_MAP(CQA_Lab_SlagEle,CL3Object)
END_L3EVENTSINK_MAP(CQA_Lab_SlagEle)

CQA_Lab_SlagEle::CQA_Lab_SlagEle(void)
{
}

CQA_Lab_SlagEle::~CQA_Lab_SlagEle(void)
{
}
