// 逻辑类TB_L3_ANACOMMISSION源文件
// 本文件是由L3集成开发环境自动生成，在没有充分了解本文件的内容前，请不要随意修改本文件中的内容
// 否则可能带来严重后果。

#include "StdAfx.h"
#include "_TB_L3_ANACOMMISSION.h"

IMPLEMENT_L3CLASS(TB_L3_ANACOMMISSION,CL3Object,1)

BEGIN_L3PROPTABLE(TB_L3_ANACOMMISSION,CL3Object)
	L3PROP_STRING(CommissionID)
	L3PROP_STRING(SampID)
	L3PROP_STRING(SampSort)
	L3PROP_STRING(SampPlace)
	L3PROP_STRING(SteelGrade)
	L3PROP_STRING(Contract)
	L3PROP_STRING(SendDate)
	L3PROP_LONG(Permit_Delete_Flag)
END_L3PROPTABLE(TB_L3_ANACOMMISSION)

BEGIN_L3METHODMAP(TB_L3_ANACOMMISSION,CL3Object)
END_L3METHODMAP()

BEGIN_L3EVENTSINK_MAP(TB_L3_ANACOMMISSION,CL3Object)
END_L3EVENTSINK_MAP(TB_L3_ANACOMMISSION)

TB_L3_ANACOMMISSION::TB_L3_ANACOMMISSION(void)
{
}

TB_L3_ANACOMMISSION::~TB_L3_ANACOMMISSION(void)
{
}
