// 逻辑类CAlloy_Data源文件
// 本文件是由L3集成开发环境自动生成，在没有充分了解本文件的内容前，请不要随意修改本文件中的内容
// 否则可能带来严重后果。

#include "StdAfx.h"
#include "_CAlloy_Data.h"

IMPLEMENT_L3CLASS(CAlloy_Data,Material,1)

BEGIN_L3PROPTABLE(CAlloy_Data,Material)
	L3PROP_DOUBLE(C)
	L3PROP_DOUBLE(Si)
	L3PROP_DOUBLE(Mn)
	L3PROP_DOUBLE(P)
	L3PROP_DOUBLE(S)
	L3PROP_DOUBLE(Cu)
	L3PROP_DOUBLE(Ni)
	L3PROP_DOUBLE(Cr)
	L3PROP_DOUBLE(Mo)
	L3PROP_DOUBLE(V)
	L3PROP_DOUBLE(Nb)
	L3PROP_DOUBLE(Al)
	L3PROP_DOUBLE(AlS)
	L3PROP_DOUBLE(Ti)
	L3PROP_DOUBLE(B)
	L3PROP_DOUBLE(Sb)
	L3PROP_DOUBLE(As)
	L3PROP_DOUBLE(Sn)
	L3PROP_DOUBLE(Zn)
	L3PROP_DOUBLE(Ca)
	L3PROP_DOUBLE(W)
	L3PROP_DOUBLE(Pb)
	L3PROP_DOUBLE(Re)
	L3PROP_DOUBLE(Ceq)
	L3PROP_DOUBLE(N)
	L3PROP_DOUBLE(H)
	L3PROP_DOUBLE(O)
	L3PROP_DOUBLE(Other1)
	L3PROP_DOUBLE(Other2)
	L3PROP_STRING(Batch_ID)
	L3PROP_STRING(Alloy_Code)
	L3PROP_STRING(UnitID)
	L3PROP_DOUBLE(Amount)
	L3PROP_DOUBLE(CrNi)
	L3PROP_DOUBLE(CrCu)
	L3PROP_DOUBLE(CrNiCu)
	///2009-05-27 添加渣样成分
	L3PROP_STRING(TFe)
	L3PROP_STRING(FeO)
	L3PROP_STRING(SiO2)
	L3PROP_STRING(TCa)
	L3PROP_STRING(CaO)
	L3PROP_STRING(MgO)
	L3PROP_STRING(Al2O3)
	L3PROP_STRING(MnO)
	L3PROP_STRING(TiO2)
	L3PROP_STRING(P2O5)
	L3PROP_STRING(R)

	///2009-06-02 添加渣样成分
	L3PROP_STRING(AD)
	L3PROP_STRING(Ni_Co)
	L3PROP_STRING(H2O)
	L3PROP_STRING(SSL)
	L3PROP_STRING(FE2O3)
	L3PROP_STRING(G_C)
	L3PROP_STRING(RD)
	L3PROP_STRING(Ba)
	L3PROP_STRING(HFF)
	L3PROP_STRING(Sic)
	L3PROP_STRING(Si_SiO2)
	L3PROP_STRING(Y_C)
	L3PROP_STRING(Ca_MgO)
	L3PROP_STRING(K2O_Na2O)
	///2016-02-26 添加仓库分类，区分合金一库和合金二库
	L3PROP_STRING(cwarehouseid)

END_L3PROPTABLE(CAlloy_Data)

BEGIN_L3METHODMAP(CAlloy_Data,Material)
END_L3METHODMAP()

BEGIN_L3EVENTSINK_MAP(CAlloy_Data,Material)
END_L3EVENTSINK_MAP(CAlloy_Data)

CAlloy_Data::CAlloy_Data(void)
{
}

CAlloy_Data::~CAlloy_Data(void)
{
}
