// 逻辑类CBFIron源文件
// 本文件是由L3集成开发环境自动生成，在没有充分了解本文件的内容前，请不要随意修改本文件中的内容
// 否则可能带来严重后果。

#include "StdAfx.h"
#include "_CBFIron.h"

IMPLEMENT_L3CLASS(CBFIron,Material,1)

BEGIN_L3PROPTABLE(CBFIron,Material)
	L3PROP_STRING(BFID)
	L3PROP_STRING(TAP_No)
	L3PROP_STRING(TPC_No)
	L3PROP_LONG(Source)
	L3PROP_LONG(Destination)
	L3PROP_DATETIME(Production_Date)
	L3PROP_LONG(Shift)
	L3PROP_STRING(Operator)
	L3PROP_LONG(NC_Confirm_Flag)
	L3PROP_LONG(Team)
	L3PROP_LONG(Result)
	L3PROP_STRING(Sample_Place)
	L3PROP_STRING_LEN(C,30)
	L3PROP_STRING_LEN(Si,30)
	L3PROP_STRING_LEN(Mn,30)
	L3PROP_STRING_LEN(S,30)
	L3PROP_STRING_LEN(P,30)
	L3PROP_STRING_LEN(Ti,30)

	//新增残余元素成分
	//Modify by hyh 2012-03-28
	L3PROP_STRING_LEN(Sn,30)
	L3PROP_STRING_LEN(Sb,30)
	L3PROP_STRING_LEN(As,30)
	L3PROP_STRING_LEN(Pb,30)
	//End

	//add by hyh 2012-08-13 应业务方要求新增：Ni(镍)、Mo(钼)、Cu(铜) 、Cr(铬)、B(硼)、V(钒)、Al(铝)、Nb(铌)、Zn(锌)、W(钨)
	L3PROP_STRING_LEN(Ni,30)
	L3PROP_STRING_LEN(Mo,30)
	L3PROP_STRING_LEN(Cu,30)
	L3PROP_STRING_LEN(Cr,30)
	L3PROP_STRING_LEN(B,30)
	L3PROP_STRING_LEN(V,30)
	L3PROP_STRING_LEN(Al,30)
	L3PROP_STRING_LEN(Nb,30)
	L3PROP_STRING_LEN(Zn,30)
	L3PROP_STRING_LEN(W,30)
	//end

	L3PROP_FLOAT(Gross_Weight)
	L3PROP_FLOAT(Last_Tare)
	L3PROP_FLOAT(Curr_Tare)
	L3PROP_FLOAT(Net_Weight)
	L3PROP_DOUBLE(Spare_Weight)
	L3PROP_LONG(IronStatus)
	L3PROP_DATETIME(Arrival_Time)
	L3PROP_DATETIME(Feed_Time)
	L3PROP_DATETIME(Send_Time)
	L3PROP_STRING(SampCode)
	L3PROP_LONG(IronConfirm)
	L3PROP_STRING_LEN(C_B,30)
	L3PROP_STRING_LEN(Si_B,30)
	L3PROP_STRING_LEN(Mn_B,30)
	L3PROP_STRING_LEN(S_B,30)
	L3PROP_STRING_LEN(P_B,30)
	L3PROP_STRING_LEN(Ti_B,30)

	//新增前残余元素成分
	//Modify by hyh 2012-03-28
	L3PROP_STRING_LEN(Sn_B,30)
	L3PROP_STRING_LEN(Sb_B,30)
	L3PROP_STRING_LEN(As_B,30)
	L3PROP_STRING_LEN(Pb_B,30)
	//End

	//add by hyh 2012-08-13 应业务方要求新增：Ni(镍)、Mo(钼)、Cu(铜) 、Cr(铬)、B(硼)、V(钒)、Al(铝)、Nb(铌)、Zn(锌)、W(钨)
	L3PROP_STRING_LEN(Ni_B,30)
	L3PROP_STRING_LEN(Mo_B,30)
	L3PROP_STRING_LEN(Cu_B,30)
	L3PROP_STRING_LEN(Cr_B,30)
	L3PROP_STRING_LEN(B_B,30)
	L3PROP_STRING_LEN(V_B,30)
	L3PROP_STRING_LEN(Al_B,30)
	L3PROP_STRING_LEN(Nb_B,30)
	L3PROP_STRING_LEN(Zn_B,30)
	L3PROP_STRING_LEN(W_B,30)
	//end

	L3PROP_LONG(GrossFlag)
	L3PROP_LONG(TareFlag)
	L3PROP_LONG(AnalysisFlag)
	L3PROP_STRING(Operator_B)
	L3PROP_LONG(DeSFlag)
	L3PROP_LONG(DeSType)
END_L3PROPTABLE(CBFIron)

BEGIN_L3METHODMAP(CBFIron,Material)
END_L3METHODMAP()

BEGIN_L3EVENTSINK_MAP(CBFIron,Material)
END_L3EVENTSINK_MAP(CBFIron)

CBFIron::CBFIron(void)
{
}

CBFIron::~CBFIron(void)
{
}
